<form action="index.php" method="post">
    <fieldset>
        <label for="post-title">Titre</label>
        <input type="text" name="postTitle" id="post-title" placeholder="Écrivez votre titre"/>
    </fieldset>
    <fieldset>
        <label for="post-content">Contenu</label>
        <input type="text" name="postContent" id="post-content" placeholder="Écrivez votre contenu"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Poster" id="post-btn"/>
    </fieldset>
</form>