<form action="index.php" method="post">
    <fieldset>
        <label for="edit-post-title">Titre</label>
        <input type="text" name="editPostTitle" id="edit-post-title" placeholder="Éditez votre titre"/>
    </fieldset>
    <fieldset>
        <label for="edit-post-content">Contenu</label>
        <input type="text" name="editPostContent" id="edit-post-content" placeholder="Éditez votre contenu"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Éditer" id="edit-post-btn"/>
    </fieldset>
</form>