<form action="index.php" method="post">
    <fieldset>
        <label for="edit-post-category-title">Titre</label>
        <input type="text" name="editPostCategoryTitle" id="edit-post-category-title" placeholder="Éditez votre titre"/>
    </fieldset>
    <fieldset>
        <label for="edit-post-category-content">Description</label>
        <input type="text" name="editPostCategoryContent" id="edit-post-category-content" placeholder="Éditez votre description"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Éditer" id="edit-post-btn"/>
    </fieldset>
</form>