<form action="index.php" method="post">
    <fieldset>
        <label for="post-category-title">Titre</label>
        <input type="text" name="postCategoryTitle" id="post-category-title" placeholder="Écrivez votre titre"/>
    </fieldset>
    <fieldset>
        <label for="post-category-content">Description</label>
        <input type="text" name="postCategoryContent" id="post-category-content" placeholder="Écrivez votre description"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Poster" id="post-btn"/>
    </fieldset>
</form>