<form action="index.php" method="post">
    <fieldset>
        <label for="user-email">Email</label>
        <input type="email" name="userEmail" id="user-email" placeholder="Entrez votre adresse email"/>
    </fieldset>
    <fieldset>
        <label for="user-password">Mot de passe</label>
        <input type="password" name="userPassword" id="user-password" placeholder="Entrez votre mot de passe"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Connexion" id="connect- btn"/>
    </fieldset>
</form>