<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini projet J7</title>
</head>
<body>
    
    <?php
        
        require 'partials/_header.phtml';
    
        require $template."/".$template.".phtml";
        
        require 'partials/_footer.phtml';
        
    ?>
        
</body>
</html>
       